config/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('photo.urls')),
    path('accounts/', include("accounts.urls"))
]

photo/urls.py
from django.urls import path
from .views import PhotoList, PhotoDelete, PhotoDetail, PhotoUpdate, PhotoCreate

app_name = "photo"
urlpatterns = [
    path("create/", PhotoCreate.as_view(), name='create'),
    path("delete/<int:pk>", PhotoDelete.as_view(), name='delete'),
    path("update/<int:pk>", PhotoUpdate.as_view(), name='update'),
    path("detail/<int:pk>", PhotoDetail.as_view(), name='detail'),
    path("", PhotoList.as_view(), name='index'),
]

from django.conf.urls.static import static

from django.conf import settings

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

photo/models.py
from django.db import models
from django.contrib.auth.models import User
from django.urls import reverse


class Photo(models.Model):
    author = models.ForeignKey(User, on_delete=models.CASCADE, related_name='user')
    text = models.TextField(blank=True)
    image = models.ImageField(upload_to = 'timeline_photo/%Y/%m/%D')
    created = models.DateTimeField(auto_now_add=True)
    updated = models.DateTimeField(auto_now=True)

    def __str__(self):
        return "text :" + self.text

    class Meta:
        ordering = ['-created']

    def get_absolute_url(self):
        return reverse('photo:detail', args=[self.id])

photo/views.py
from django.shortcuts import redirect, render
from django.views.generic.base import RedirectView
from django.views.generic.list import ListView
from django.views.generic.edit import CreateView, DeleteView, UpdateView
from django.views.generic.detail import DetailView
from .models import Photo
from django.http import HttpResponseRedirect
from django.contrib import messages

class PhotoList(ListView):
    model = Photo
    template_name_suffix = '_list'

class PhotoCreate(CreateView):
    model =Photo
    fields = ['author', 'text', 'image']
    template_name_suffix = '_create'

    def form_valid(self, form):
        form.instance.author_id = self.request.user.id
        if form.is_valid():
            #올바르다면
            # form : 모델폼
            form.instance.save()
            return redirect('/')
        else:
            #올바르지 않다면
            return self.render_to_response({'form':form})    

class PhotoUpdate(UpdateView):
    model = Photo
    fields = ['author', 'text', 'image']
    template_name_suffix = '_update'
    # success_url = '/'

    def dispatch(self, request, *arg, **kwargs):
        object = self.get_object()
        if object.author != request.user:
            message.warning(request, '수정 권한이 없습니다.')
            return HttpResponseRedirect('/')

        else:
            return super(PhotoUpdate, self).dispatch(request, *arg, **kwargs)


class PhotoDelete(DeleteView):
    model = Photo
    template_name_suffix = '_delete'
    success_url = '/'

    def dispatch(self, request, *arg, **kwargs):
        object = self.get_object()
        if object.author != request.user:
            message.warning(request, '삭제 권한이 없습니다.')
            return HttpResponseRedirect('/')
        else:
            return super(PhotoDelete, self).dispatch(request, *arg, **kwargs)

class PhotoDetail(DetailView):
    model = Photo
    template_name_suffix = '_detail'

photo/templates/photo/photo_create.html
{% extends 'base.html' %}
{% block content %}
<div class="row">
    <div class="col"></div>
    <div class="col-12 col-xl-8 col-md-8">
        <div class="alert alert-primary" role="alert">
            빈칸이 없도록 모두 입력하세요.
        </div>
        <form action="" method="post" enctype="multipart/form-data">
            {% csrf_token %}

            {{form.as_p}}
            <input type="submit" value="Upload" class="btn btn-primary">
        </form>
    </div>
    <div class="col"></div>
</div>
{% endblock %}

photo/templates/photo/photo_delete.html
{% extends 'base.html' %}
{% block content %}

<div class="alert alert-primary" role="alert">
    정말 {{object}}를 삭제 하시겠습니까?
</div>
<form action="" method="post">
    {% csrf_token%}
    <input type="submit" value="Delete OK">
</form>
{% endblock %}

photo/templates/photo/photo_detail.html
{% extends 'base.html' %}

{% block title %}
{% endblock %}

{% block content %}
<div class="row">
    <div class="col"></div>
    <div class="col-12 col-xl-4 col-md-4">
        <div class="card" style="width: 30rem;">
            <img src=" {{ object.image.url }} " class="card-img-top" alt="...">
            <div class="card-body">

                <h5 class="card-title">{{ object.author }}</h5>
                <p class="card-text"> {{ object.text }}</p>
            </div>
            <ul class="list-group list-group-flush">
                <li class="list-group-item">생성일 : {{ object.updated }}</li>
                <li class="list-group-item">
                    {% load disqus_tags %}
                    <div class="card-body">
                        {% disqus_show_comments %}
                    </div>
                </li>
            </ul>
            <div class="card-body">
                <a href="{% url 'photo:update' object.id %}" class="card-link">수정하기</a>
                <a href="{% url 'photo:delete' object.id %}" class="card-link">삭제하기</a>
            </div>
        </div>
    </div>

    <div class="col"></div>
</div>
{% endblock %}

photo/templates/photo/photo_list.html
{% extends 'base.html' %}

{% block title %}
{% endblock%}

{% block content %}
<div class='container'>
    <div class ='row'>
        <div class="col"></div>
        <div class="col-5">
            {% for object in object_list %}
        
            <div class="card">
                <div class="card-header">
                    {{ object.author }}
                </div>
                <img src=" {{ object.image.url }}" class="card-img-top" alt="...">
                <div class="card-body">
                    <p class="card-text"> {{ object.text }} </p>
                </div>
                <ul class="list-group list-group-flush">
                    
                    <li class="list-group-item">생성일 : {{ object.created }}</li>
                    <li class="list-group-item">수정일 : {{ object.updated }}</li>
                </ul>
                <div class="card-body">
                    <a href="{% url 'photo:detail' object.id %}" class="card-link">댓글달기</a>
                    {% if user == object.author %}
                    <a href="{% url 'photo:update' object.id %}" class="card-link">수정하기</a>
                    <a href="{% url 'photo:delete' object.id %}" class="card-link">삭제하기</a>
                    {% endif%}
                </div>
            </div>
            {% endfor %}
        </div>
        
        <div class="col"></div>
    </div>
</div>
{% endblock %}

photo/templates/photo/photo_update.html
{% extends 'base.html' %}
{% block content %}
<div class="row">
    <div class="col"></div>
    <div class="col-12 col-xl-8 col-md-8">
        <form action="" method="post">
            {% csrf_token %}
            {{form.as_p}}
            <input type="submit" value="Create">
        </form>
    </div>
    <div class="col"></div>
</div>
{% endblock %}